### ISSUE TITLE
Loop stops

### ISSUE THREAD

**Issue by BitBargain** [clue/reactphp-block#44]
Shortly after using any of the functions (await, awaitAll, even sleep) the app stops. It simply finishes when the current stack is done. If I remove the \Block function and replace it with a dummy, it works just fine. Even when I don't remove it, it works as expected, the promise resolves successfully and it's returned properly. But when the loop goes to the end, it stops, I presume because of the loop->stop() part in the source.

Am I doing something wrong? Any suggestions would be appreciated.

"react/event-loop": "^1.1"
"clue/block-react": "^1.3"

PHP 7.2.24-0ubuntu0.19.04.1 (cli) (built: Oct 24 2019 11:49:39) ( NTS )

**Comment by clue** [comment]
@BitBargain Thanks for reporting, this has been discussed in https://github.com/clue/reactphp-block/issues/20 before and I'm afraid there's not much we can do about this.

As a rule of thumb, mixing blocking and non-blocking code should be avoided. This means these functions should only be used in a blocking application. If you're using a non-blocking application, you should use non-blocking primitives provided by promises and event emitters.

I hope this helps :+1:

**Comment by markkimsal** [comment]
@BitBargain I was bitten by this too when I first looked at this library.

I thought it was just a design choice, but it really is impossible to mix blocking and non-blocking.

If your application is not driven by the main async loop entirely, you will end up in an infinite loop waiting for some kind of socket activity.  If you don't have any more promises or timers left, the only thing the async loop can do is wait around for socket or unix signals (ctrl-c).

So, when you're in a blocking application, you just have to fire the loop for your one async library call and then kill it.

**Comment by BitBargain** [comment]
I'm happy to report the problem has been solved, though the event loop itself needs to be touched.

1) In react/even-loop, add to ExtUvLoop.php (or any event loop):
`
    public function restart()
    {
        $this->running = true;
    }
`
2) In clue/block-react, add to functions.php (after the while ($wait) loop->run() part):
`$loop->restart();`

It works perfectly fine now. I'm wondering - am I really the only one who needed this functionality? Did I do something terrible here or is this something that could be posted to react/event-loop for this "restart" functionality to be included?

**Comment by clue** [comment]
@BitBargain Thanks for looking into this and confirming our observation :+1:

I think we agree that mixing blocking and non-blocking calls is probably not the best idea and should only be used as a last resort. It's usually recommended to set up a dedicated loop instance within some blocking function so that it will not affect anything outside of this scope.

**Comment by BitBargain** [comment]
The reason I didn't get it at first (and I'm explaining this to potentially save time for someone else) was because \Block isn't actually blocking, it keeps running the app through $loop->run(). That's why I figured it may be feasible to use it. And it works, too, you just can't resolve a lower-level block before a higher level one. And that sort of kills the point, except for a few edge cases with certain logic involved where no two blocks are used at the same time (or they're resolved in perfect order).

**Comment by JABirchall** [comment]
I ran into this issue just now, this is the first time using this library as I needed to have a separate promise conditionally run to resolve missing data. 

Simply wrapping $loop->run() in a while loop solved the problem for me.

**Comment by JABirchall** [comment]
I had a requirement to use this library to pause execution in a promise if certain data is missing to run another promise to fetch the data and continue execution once the data is present. 

But is this really the "incorrect" usage? as the previous comment states, the loop is still running, and all my events, timers and listeners still work, just the caveat that the loop stops after the await function call. 

But In my usage, since it's a continually running app I just wrapped my $loop->run() in a while loop to keep it running after calling await. I've experienced no problems so far.
