### ISSUE TITLE
Loop terminates when sleep time is reached

### ISSUE THREAD

**Issue by bcremer** [clue/reactphp-block#49]
When calling `Clue\React\Block\sleep` within a HTTP Server loop the loop terminates after the timeout

## Repo

```bash
$ cat composer.json 
{
    "require": {
        "react/http": "^1.0",
        "clue/block-react": "^1.3"
    }
}
```

```php
<?php

use Psr\Http\Message\ServerRequestInterface;
use React\Http\Message\Response;

use function Clue\React\Block\sleep;

require __DIR__ . '/vendor/autoload.php';

$loop = React\EventLoop\Factory::create();

$server = new React\Http\Server($loop, static function (ServerRequestInterface $request) use ($loop) {
    $duration = 1.5;
    echo sprintf("Sleeping for %F\n", $duration);
    sleep(1.5, $loop);
    echo "After Sleep";

    return new Response(200, [], 'Some reponse');
});

$socket = new React\Socket\Server('127.0.0.1:8080', $loop);
echo "Server running at http://127.0.0.1:8080\n";

$server->listen($socket);
$loop->run();
```

```bash
$ php repro.php
Server running at http://127.0.0.1:8080
Sleeping for 1.500000
After Sleep%    # process terminated
```

```bash
$ curl  "http://localhost:8080/"
curl: (52) Empty reply from server
```

When the call to `sleep` is removed the loop does not exit like expected:

```bash
$ php repro.php
Server running at http://127.0.0.1:8080
```

```bash
$ curl  "http://localhost:8080/"                                                   
Some reponse%
$ curl  "http://localhost:8080/"
Some reponse%      
```

**Comment by bcremer** [comment]
Closing this issue as per https://twitter.com/giveupalready/status/1287748428861186049.

**Comment by clue** [comment]
@bcremer Already answered via the referenced Twitter thread, but thanks for asking here anyway!

This has been discussed in #20, #44 and others before and this is more or less by design.

As a rule of thumb, mixing blocking and non-blocking code should be avoided. This means these functions should only be used in a blocking application. If you're using a non-blocking application, you should use non-blocking primitives provided by promises and event emitters.

In your case this means that `$loop->addTimer()` should be used instead of a blocking `sleep()`.

I hope this helps :+1:
